name: CI

on:
  push:
  pull_request:
    branches: '*'

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.arch }} - Build mode ${{ matrix.build_mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86, x86_64]
        build_mode: ["", -Drelease-fast, -Drelease-safe, -Drelease-small]

    steps:
    - uses: actions/checkout@v1
    
    - name: Download zig (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://ziglang.org/download/0.16.0/zig-windows-x86_64-0.16.0.zip" -OutFile "zig.zip"
        Expand-Archive -Path zig.zip -DestinationPath .
    
    - name: Check formatting (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: zig-windows-x86_64-0.16.0/zig.exe fmt --check src
    
    - name: Build kernel (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: zig-windows-x86_64-0.16.0/zig.exe build ${{ matrix.build_mode }} -Dtarget=${{ matrix.arch }}
    
    - name: Run unit tests (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: zig-windows-x86_64-0.16.0/zig.exe build test ${{ matrix.build_mode }} -Dtarget=${{ matrix.arch }}
